openapi: "3.0.2"
info:
  title: server
  version: "1.0"
servers:
  - url: http://localhost:8080
paths: {}
components:
  requestBodies: {}
  responses: {}
  examples: {}
  schemas: {}
  parameters: {}
